/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3ita_obesenec;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Krouzek
 */
public class Okno extends javax.swing.JFrame {

    private TlacitkoPismenko[] abeceda=new TlacitkoPismenko[26];
    private int velikostTlacitka=50;
    private Panel panel;
    private Sibenice sibenice=new Sibenice();
    
    public Okno() throws IOException {
        panel=new Panel(velikostTlacitka);
        initComponents();
        Klavesnice();
        RozmistiTlacitka();
        this.setSize(470, 653);
        this.setResizable(false);
        this.add(panel);
        sibenice.VypisDoLabelu(hadaneSlovo); //vypis slova do labelu
    }
    
    private void Klavesnice(){
        String abe="abcdefghijklmnopqrstuvwxyz";
        for(int i=0;i<abeceda.length;i++){
            abeceda[i]=new TlacitkoPismenko(Character.toString(abe.charAt(i)),velikostTlacitka,this);
            this.add(abeceda[i]);            
        }
    }
    private void RozmistiTlacitka(){
        int zhora=10;
        int zleva=10;
        
        for(int i=0;i<abeceda.length;i++){
            if(i%9==0){
                zhora+=velikostTlacitka;
                zleva=10;
            }
            if(i==18){
                zleva+=velikostTlacitka/2;
            }
            abeceda[i].setLocation(zleva, zhora);
            zleva+=velikostTlacitka;
        }
        
    }
    public void Hadaji(String s) throws IOException{
        //pri stisku tlacitka
        panel.Prekresli(sibenice.Hadam(s));
        sibenice.VypisDoLabelu(hadaneSlovo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hadaneSlovo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hadaneSlovo.setText("Hadane slovo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(hadaneSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hadaneSlovo)
                .addGap(0, 284, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Okno().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Okno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hadaneSlovo;
    // End of variables declaration//GEN-END:variables
}
